#define o00 #define
#define o01 0
#define o02 O
#define o03 oo
#define o04 OO
#define o05 ooo
#define o06 Oo
#define o07 oO
#define o08 OOo
#define o09 oOO
#define o10 oooO
#define o11 ooO
#define o12 Ooo
#define o13 OoO
#define o14 ooO
#define o15 OOO
#define o16 oOo
#define o17 oooOo
#define o18 OoOo
#define o19 ooOO
#define o20 oOoO
#define o21 ooOo
#define o22 OooO
#define o23 OOOo
#define o24 oOOo
#define o25 ooOOo
#define o26 OoOO
#define o27 ooOoO
#define o28 OooOo
#define o29 OOOOo
#define o30 oOOOo
#define o31 ooOOoO
#define o32 OoOOo
#define o33 ooOoOO
#define o34 OooOoO
#define o35 OOOoOo
#define o36 oOOoOo
#define o37 ooOoOo
#define o38 OoOoOo
#define o39 ooOOoOo
#define o40 OoOOoOo
#define o41 ooOoOoO
#define o42 OooOoOo
#define o43 OOOoOoO
#define o44 oOOoOoO
#define o45 ooOoOoOO
#define o46 OoOoOoO
#define o47 ooOOoOoO
#define o48 OoOOoOoO
#define o49 ooOoOoOo
#define o50 OooOoOoO
#define o51 OOOoOoOo
#define o52 oOOoOoOo
#define o53 ooOoOoOoO
#define o54 OoOoOoOo
#define o55 ooOOoOoOo
#define o56 OoOOoOoOo
#define o57 ooOoOoOoOo
#define o58 OooOoOoOo
#define o59 OOOoOoOoO
#define o60 oOOoOoOoO
#define o61 ooOoOoOoOo
#define o62 OoOoOoOoO
#define o63 ooOOoOoOoO
#define o64 OoOOoOoOoO
#define o65 ooOoOoOoOoO
#define o66 OooOoOoOoO
#define o67 OOOoOoOoOo
#define o68 oOOoOoOoOo
#define o69 ooOoOoOoOoO
#define o70 OoOoOoOoOo
#define o71 ooOOoOoOoOo
#define o72 OoOOoOoOoOo
#define o73 ooOoOoOoOoOo
#define o74 OooOoOoOoOo
#define o75 OOOoOoOoOoO
#define o76 oOOoOoOoOoO
#define o77 ooOoOoOoOoOo
#define o78 OoOoOoOoOoO
#define o79 ooOOoOoOoOoO
#define o80 OoOOoOoOoOoO
#define o81 ooOoOoOoOoOoO
#define o82 OooOoOoOoOoO
#define o83 OOOoOoOoOoOo
#define o84 oOOoOoOoOoOo
#define o85 ooOoOoOoOoOoO
#define o86 OoOoOoOoOoOo
#define o87 ooOOoOoOoOoOo
#define o88 OoOOoOoOoOoOo
#define o89 ooOoOoOoOoOoOo
#define o90 OooOoOoOoOoOo
#define o91 OOOoOoOoOoOoO
#define o92 oOOoOoOoOoOoO
#define o93 ooOoOoOoOoOoOo
#define o94 OoOoOoOoOoOoO
#define o95 ooOOoOoOoOoOoO
#define o96 OoOOoOoOoOoOoO
#define o97 ooOoOoOoOoOoOoO
#define o98 OooOoOoOoOoOoO
#define o99 OOOoOoOoOoOoOo
#define o100 oOOoOoOoOoOoOo
#define o101 ooOoOoOoOoOoOoO
#define o102 OoOoOoOoOoOoOo
#define o103 ooOOoOoOoOoOoOo
#define o104 OoOOoOoOoOoOoOo
#define o105 ooOoOoOoOoOoOoOo
#define o106 OooOoOoOoOoOoOo
#define o107 OOOoOoOoOoOoOoO
#define o108 oOOoOoOoOoOoOoO
#define o109 ooOoOoOoOoOoOoOo
#define o110 OoOoOoOoOoOoOoO
#define o111 ooOOoOoOoOoOoOoO
#define o112 OoOOoOoOoOoOoOoO
#define o113 ooOoOoOoOoOoOoOoO
#define o114 OooOoOoOoOoOoOoO
#define o115 OOOoOoOoOoOoOoOo
#define o116 oOOoOoOoOoOoOoOo
#define o117 ooOoOoOoOoOoOoOoO
#define o118 OoOoOoOoOoOoOoOo
#define o119 ooOOoOoOoOoOoOoOo
#define o120 OoOOoOoOoOoOoOoOo
#define o121 ooOoOoOoOoOoOoOoOo
#define o122 OooOoOoOoOoOoOoOo
#define o123 OOOoOoOoOoOoOoOoO
#define o124 oOOoOoOoOoOoOoOoO
#define o125 ooOoOoOoOoOoOoOoOo
#define o126 OoOoOoOoOoOoOoOoO
#define o127 ooOOoOoOoOoOoOoOoO
#define o128 OoOOoOoOoOoOoOoOoO
#define o129 ooOoOoOoOoOoOoOoOoO
#define o130 OooOoOoOoOoOoOoOoO
#define o131 OOOoOoOoOoOoOoOo